### ISSUE TITLE
Exclude folder during update

### ISSUE THREAD

**Issue by StoicPerlman** [phonegap-build/pgb-cli#10]
Is there a way to exclude a folder from the archive when doing `pgb update ##### .`?

**Comment by goya** [comment]
nope. not at the moment

**Comment by goya** [comment]
added support for 
```bash
> pgb update 12 ./path --ignore "node_modules" --ignore "*.lock" --ignore "tmp"
```
you can also put a file called .pgbrc in the root of your application directory.  this file should be json format and can be this:
```json
{ "ignore": [ "node_modules", "*.lock", "tmp" ] }
```
i'll close this out when the npm package is published

**Comment by StoicPerlman** [comment]
Awesome. I had started looking at this and was thinking of swapping out the zip module you were using because it didn't look to support excludes. Thanks for the fast turn around on that.
