### ISSUE TITLE
Call pgb update without triggering a build

### ISSUE THREAD

**Issue by rgagne** [phonegap-build/pgb-cli#12]
I'd like to be able to call update without triggering a build. Reason for this is I'd like to set the build key (in case they changed) and upload the build.

The first update triggers a build (with the prior code) and the second update triggers a build with the new code. I tried -e, but that seems to still trigger a build. 

pgb update <id> ios-key=<key>
pgb update <id> ./build.zip

Thank you!

**Comment by goya** [comment]
you can add properties and update source at the same time
```bash
> pgb update 12 ./path_to_zip_or_dir ios-key=1213
```

**Comment by rgagne** [comment]
That did it - thank you!
