### ISSUE TITLE
Relation with phonegap-cli

### ISSUE THREAD

**Issue by bangseongbeom** [phonegap-build/pgb-cli#13]
[phonegap-cli] and its API module [node-phonegap-build] are already providing PhoneGap Build features via `phonegap remote`.

Of course `phonegap remote` has very limited features and it is outdated. but I can't assume the reason why don't just update/enrich those tools, instead of reinventing [pgb-cli] and [pgb-api].

I'm not sure that [pgb-cli] is recommended way in current state, and `phonegap remote` will be replaced eventually.

[phonegap-cli]: https://github.com/phonegap/phonegap-cli
[node-phonegap-build]: https://github.com/phonegap/node-phonegap-build
[pgb-cli]: https://github.com/phonegap-build/pgb-cli
[pgb-api]: https://github.com/phonegap-build/pgb-api

**Comment by goya** [comment]
i assume phonegap remote will be replaced with this, as it has more functionality like you said. it’s on our roadmap depending on pending cordova releases
