### ISSUE TITLE
Args with hyphen (-) are not being treated

### ISSUE THREAD

**Issue by crazyserver** [phonegap-build/pgb-cli#14]
parseArgs function is not parsing well the args with a hyphen. cliOpts doesn't have any hypens but on parseArgs they are not replaced.

**Comment by crazyserver** [comment]
i.e --exit-code is not working but --exitcode yes.

**Comment by crazyserver** [comment]
I think this can be solved adding a replage like .replace(/-/, '') before checking if opts.flags[flag] exists.
or changing the key of the flags.

**Comment by goya** [comment]
good catch!
