### ISSUE TITLE
Declare platforms to build on pgb clone

### ISSUE THREAD

**Issue by crazyserver** [phonegap-build/pgb-cli#17]
If you want to build only one platform the clone command will build both and fail if the other platform is not well configured (ie not unlocked).

I tried using update and build separately but two builds are launched (update always  make a build (it would be great to omit the build).

So, my current status is: I want to build for ios and android will be launched and will fail because is locked.

**Comment by goya** [comment]
you can just specify <platform name="ios" /> with no other platform tag present and it will only build ios.

this is a limitation of the api on build.phonegap.com's side.

**Comment by crazyserver** [comment]
Do you know if something changed on the API? When using clone with android-key, sometimes the key does not change and the build fails (since 2-3 weeks ago)
