### ISSUE TITLE
pgb update or clone does not pull latest changes

### ISSUE THREAD

**Issue by crazyserver** [phonegap-build/pgb-cli#18]
I'm using the command:
 pgb update --exit-code --no-progress tag=$branch

to generate a build on PGB (also tried the same with pgb clone)

Settings are changed correctly but info about the build (i.e title and real code) is not updated, so build will be made without updating code from the branch.

The workarround is to manually enter PGB website and click on Pull latest.

**Comment by crazyserver** [comment]
We've realised that not only fails with branch/tag change. Also is not getting the latest commit it always take the commit from the last execution.

**Comment by goya** [comment]
try `pgb clone`

**Comment by crazyserver** [comment]
Thanks Brett!

As I said in the first comment pgb clone has the same  result. In fact out scripts have are using pgb clone so this is already tried.

This is the script we are running from Travis CI to build the app:

https://github.com/moodlehq/moodlemobile-phonegapbuild/blob/integration/scripts/pgb.sh

After we commit there, Travis logins, unlock and build the app. But the latest commit is never used. Instead is used the previous run commit. After that we have to manually push "Update code" from the PGB website to manually build it.

Thanks for your time!

**Comment by crazyserver** [comment]
Hmm looking at the code the problem could be related to pgb-api instead of pgb-cli.
