### ISSUE TITLE
pgb update --exit-code always returns exit code 1

### ISSUE THREAD

**Issue by codemasterover9000** [phonegap-build/pgb-cli#2]
When running a shell script containing:

    pgb -c update --exit-code $PHONEGAP_APP_ID $PHONEGAP_SOURCE_LOCATION \
     ios-key=$PHONEGAP_IOS_KEY_ID \
     android-key=$PHONEGAP_ANDROID_KEY_ID
    echo "exit code: $PIPESTATUS"

the output is always:
```
archiving 100% [########################################] 125.4 MB / 125.4 MB
uploading 100% [########################################] 36.3 MB / 36.3 MB
app 9999999 updated
-------------------------
 App Id: 9999999
-------------------------
Android: SUCCESS            
    iOS: SUCCESS            
Windows: SKIPPED            
-------------------- 0:57
exit code: 1
```

This makes it impossible to detect success without resorting to parsing the output.

system info:
```
$ node --version
v8.10.0
$ npm --version
5.6.0
$ uname -a
Linux slack 4.4.118 #1 SMP Sun Feb 25 14:18:45 CST 2018 x86_64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz GenuineIntel GNU/Linux
```

**Comment by goya** [comment]
rookie mistake!  thanks for catching this abomination.
