### ISSUE TITLE
Is there way to automate keys unlocking?

### ISSUE THREAD

**Issue by isupovs** [phonegap-build/pgb-cli#3]
How can I specify keystore/private passwords to avoid password prompt?

**Comment by goya** [comment]
You can specify these as env variables:
```bash
PGB_KEY_PASSWORD # android, ios, windows
PGB_KEY_KEYSTORE_PASSWORD # android
```

eg.

```
export PGB_KEY_PASSWORD=abc
export PGB_KEYSTORE_PASSWORD=def
pgb unlock-key android 12
```

if you dont want prompts for ```pgb new key``` then use the ```--no-unlock``` flag and the key will be created but not unlocked.

**Comment by isupovs** [comment]
Thanks, it works great. For windows ` set PGB_KEY_PASSWORD=abc`
