### ISSUE TITLE
it opens and closes again!

### ISSUE THREAD

**Issue by rooz121359** [phonegap-build/pgb-cli#4]
Hi,

I tried to open the .exe file on my windows 10 and everytime i open it, it closes again immediately.

**Comment by goya** [comment]
the pgb.exe is just a wrapper around the nodejs application so it's just a terminal application, there is no GUI so it must be run from the command line.
```bash
Start > Windows PowerShell
or
Start > cmd
```

then the cli can be run in the terminal program by 
```bash
> pgb.exe ls 
```
