### ISSUE TITLE
Using pgb unlock

### ISSUE THREAD

**Issue by cjpit** [phonegap-build/pgb-cli#8]
Hi there, I'm trying to use the unlock method with a CI Gitlab setup.  Unfortunately it always prompts for the keystore password and key passwrod - it seems to delete the env variables that could have possibly been passed in.
Any reason why this is the case?

Thanks

**Comment by goya** [comment]
i havent used the gitlab CI. maybe try just echo'ing the env vars to ensure theyre there.

**Comment by cjpit** [comment]
Yeah the env vars are there, maybe I just don't understand how to unlock.
It is getting the error android key xxxxx not found (maybe wrong platform?)
I'm doing 
pgb unlock android appid

**Comment by goya** [comment]
are you using the “key id”? this error is server side so id is incorrect.

**Comment by cjpit** [comment]
How do I find the key id? I can't seem to find the value anywhere on the interface online

**Comment by goya** [comment]
```bash
> pgb keys android
```

**Comment by cjpit** [comment]
Thank you worked like a charm, it is now auto deploying to google play store, thanks for your help!
